### ISSUE TITLE
[ S1 - PB1] Register

### ISSUE THREAD

**Issue by rahelyohana** [SI-RPL-2023/SI4407_KEL259_SHARETY#1]

**Comment by rahelyohana** [comment]
User melakukan pendaftaran akun untuk bisa login kepada aplikasi.


![Image](https://user-images.githubusercontent.com/115544647/228452300-f8c2d79d-e63f-4272-ac61-3481c0053d8f.png)

**Comment by mrezairfandi** [comment]
done
